### ISSUE TITLE
expectの書き方

### ISSUE THREAD

**Issue by shihou-ono** [apc-nw-auto-cft/auto_check_config_project#8]
現状では状態を評価するために取得するcommandが固定されているし、当然評価も1つしかできない。

```yaml
# expect
---
before:
  expect_via_interface: "ge-0/0/0.0"
after:
  expect_via_interface: "ge-0/0/2.0"
```

それを、このように、取得するcommandと想定状態をexpectに書いてしまい、

```yaml
# expect
---
expect:
  - command: "show route 10.100.100.2"
    query: "['route-information'][0]['route-table'][0]['rt'][0]['rt-entry'][0]['nh'][0]['via'][0]['data']"
    result:
      before: "ge-0/0/0.0"
      after: "ge-0/0/2.0"
  - command: "show int terse ge-0/0/1"
    query: "良い感じに掘ってく"
    result:
      before: "down"
      after: "down"
```

こんな感じでshow commandを取得していく
```yaml
---
- name: "get route"
  junipernetworks.junos.junos_command:
    commands: "{{ item.command }}"
    display: json
  register: res_show
  loop: "{{ expect }}"
```
